export const talentPoolData1 = [
    {
        "id": "5878995929",
        "properties": {
            "custom_talent_category": "Controlling [Finanzwesen]",
            "hs_createdate": "11/06/24",
            "t_candidate_id": "49458",
            "t_city": "Vorrangig Berlin, dann Frankfurt, München, Luxembourg",
            "t_current_position": "Analyst Renewable Energy & Strategic Development",
            "t_desired_region_1": "Berlin",
            "t_desired_salary": "65000",
            "t_experience_level": "Medior (3-7 Jahre)",
            "t_maincategory": "Finanzwesen",
            "t_procedure_txt": "",
            
        }
    },
    {
        "id": "5879336431",
        "properties": {
            "custom_talent_category": "Property, Center & Facility Management",
            "hs_createdate": "11/06/24",
            "hs_lastmodifieddate": "14/05/25",
            "hs_object_id": "5879336431",
            "t_availability": "2 Wochen",
            "t_candidate_id": "49566",
            "t_city": "Düsseldorf, Köln mit Home Office",
            "t_current_position": "Senior Property Managerin",
            "t_current_position_group": "Immobilienwesen",
            "t_desired_region_1": "Nordrhein-Westfalen",
            "t_desired_region_2": "",
            "t_desired_region_3": "",
            "t_desired_salary": "65000",
            "t_education_background": "<ul>\n<li>Ausbildung Umschulung zur Immobilienkauffrau</li>\n<li>Fachhochschulreife</li>\n</ul>",
            "t_experience_level": "Medior (3-7 Jahre)",
            "t_maincategory": "Immobilienwesen",
            "t_procedure_txt": "",
            "t_salary_period": "pro Jahr",
            "t_specialized_focus": "<ul>\n<li>Erste fundierte Expertise in der kaufm&auml;nnischen Immobilienverwaltung von Gewerbe- (B&uuml;ro, Einzelhandel) und Wohnimmobilien sowie gemischt genutzten Objekten (multi- und single-tenant)</li>\n<li>Enge Zusammenarbeit mit dem Asset Management inklusive Reporting</li>\n<li>Pr&uuml;fen und Anlegen von Mietvertr&auml;gen</li>\n</ul>"
        }
    },
    {
        "id": "5879787463",
        "properties": {
            "custom_talent_category": "Property, Center & Facility Management [Bauwesen]",
            "hs_createdate": "11/06/24",
            "hs_lastmodifieddate": "22/05/25",
            "hs_object_id": "5879787463",
            "t_availability": "3 Monate zum Monatsende",
            "t_candidate_id": "49528",
            "t_city": "Frankfurt",
            "t_current_position": "Consultant Immobilienbewertung",
            "t_current_position_group": "Bau- & Technisches Immobilienwesen",
            "t_desired_region_1": "Hessen",
            "t_desired_salary": "65000",
            "t_education_background": "<ul>\n<li>Masterabschluss (M.A.) Real Estate Economics</li>\n<li>Internationales Immobilienmanagement (B.A.)</li>\n</ul>",
            "t_experience_level": "Senior (7-15 Jahre)",
            "t_it_skills": "<ul>\n<li>Microsoft Office</li>\n</ul>",
            "t_maincategory": "Bauwesen",
            "t_procedure_txt": "Permanent",
            "t_salary_period": "pro Jahr",
            "t_specialized_focus": "<ul>\n<li>Mehrj&auml;hrige Berufserfahrung innerhalb der Immobilienbranche mit Fokus auf die Evaluation</li>\n<li>Erstellung von Wertgutachten (Marktwertermittlung nach deutschen Verfahren, DCF, Beleihungswertermittlung)</li>\n<li>Erster Ansprechpartner f&uuml;r die Kunden entlang der Bewertung (Kundenfokus Projektentwickler & institutionelle Kunden)</li>\n<li>Verschiedene Nutzungsklassen: B&uuml;ro, Retail, Logistik, Wohnen</li>\n<li>Markt-, Standort-, Wettbewerbsanalysen</li>\n</ul>"
        }
    },
    {
        "id": "5881205478",
        "properties": {
            "custom_talent_category": "Leitungsfunktionen",
            "hs_createdate": "11/06/24",
            "hs_lastmodifieddate": "08/04/25",
            "hs_object_id": "5881205478",
            "t_availability": "Nach Absprache zum Jahresende",
            "t_candidate_id": "49359",
            "t_city": "München, Frankfurt, Düsseldorf, Hamburg, Berlin, Stuttgart, Köln",
            "t_current_position": "Geschäftsführer / Syndikusrechtsanwalt",
            "t_current_position_group": "Immobilienwesen",
            "t_desired_region_1": "Bundesweit",
            "t_desired_salary": "140000",
            "t_education_background": "<ul>\n<li>Erstes und zweites juristisches Staatsexamen</li>\n<li>Allgemeine Hochschulreife</li>\n</ul>",
            "t_experience_level": "Senior (7-15 Jahre)",
            "t_maincategory": "Immobilienwesen",
            "t_procedure_txt": "",
            "t_salary_period": "pro Jahr",
            "t_specialized_focus": "<ul>\n<li>Diverse Verantwortung als Gesch&auml;ftsf&uuml;hrer in den Bereichen Transaktion, Projektentwicklung, Finanzen und Recht</li>\n<li>Fachliche und disziplinarischer F&uuml;hrungsverantwortung von ca. acht Mitarbeitenden</li>\n<li>Involviert in alle entscheidenden Prozesse der DD und aktive Durchf&uuml;hrung von Immobilienank&auml;ufen, durch Generalvollmacht verbrieft und abgeschlossen</li>\n<li>Ankauf (inkl. Marketing und Vertriebssteuerung) von 27 Geb&auml;uden (Wohnen und MFH) seit 2011 mit Volumen zwischen EUR 6 Mio. und EUR 12 Mio. pro Einheit, vereinzelt Gewerbefl&auml;chen (B&uuml;ro- und Ladenfl&auml;chen)</li>\n<li>Immobilien- und Baurecht, Steuerrecht und Gesellschaftsrecht</li>\n</ul>"
        }
    },
    {
        "id": "5881315831",
        "properties": {
            "custom_talent_category": "Vertrieb",
            "hs_createdate": "11/06/24",
            "hs_lastmodifieddate": "14/05/25",
            "hs_object_id": "5881315831",
            "t_availability": "3 Monate zum Monatsende",
            "t_candidate_id": "49381",
            "t_city": "Frankfurt, Berlin, eventuell Top7",
            "t_current_position": "Fund & Acquisition Managerin",
            "t_current_position_group": "Immobilienwesen",
            "t_desired_region_1": "Hessen",
            "t_desired_region_2": "Bundesweit",
            "t_desired_salary": "90000",
            "t_education_background": "<ul>\n<li>Master's Degree (M.Sc.) in International Finance</li>\n<li>Bachelor's Degree (B.Sc.) in Finance, Banking and Insurance</li>\n<li>High School Graduate</li>\n<li>Doctoral Programme (PhD.) in Economics</li>\n</ul>",
            "t_experience_level": "Medior (3-7 Jahre)",
            "t_maincategory": "Immobilienwesen",
            "t_procedure_txt": "",
            "t_salary_period": "pro Jahr",
            "t_specialized_focus": "<ul>\n<li>Acquisition Management f&uuml;r mehrere verschiedene europ&auml;ische</li>\n<li>Fokus auf Residential Deutschland, &Ouml;sterreich, Niederlande, Spanien, Italien und Portugal (f&uuml;r Versorgungswerke, Pensionskassen, Banken)</li>\n<li>Pr&uuml;fung und Kalkulation von potenziellen Angeboten</li>\n<li>Core bis Core+ bis Value Add</li>\n<li>Hohe analytische F&auml;higkeiten</li>\n<li>Steuerung der Due Diligence</li>\n<li>Fund Management f&uuml;r &Uuml;berwachung von Asset-Management-Maßnahmen</li>\n<li>Auswahl der Dienstleister</li>\n<li>Enge Zusammenarbeit mit der externen Service-KVG</li>\n<li>Vorbereitung von Reportings</li>\n</ul>"
        }
    },
    {
        "id": "5949112812",
        "properties": {
            "custom_talent_category": "Controlling [Finanzwesen]",
            "hs_createdate": "12/06/24",
            "hs_lastmodifieddate": "14/05/25",
            "hs_object_id": "5949112812",
            "t_availability": "2 Monate zum Monatsende",
            "t_candidate_id": "46619",
            "t_city": "Berlin",
            "t_current_position": "Referent Controlling",
            "t_current_position_group": "Finanzwesen & Personal",
            "t_desired_region_1": "Berlin",
            "t_desired_salary": "80000",
            "t_education_background": "<ul>\n<li>Weiterbildung zum Bilanzbuchhalter IHK</li>\n<li>Weiterbildung in Bilanzierung nach IFRS</li>\n<li>Diplom in Betriebswirtschaftslehre</li>\n<li>Studium Volkswirtschaftslehre</li>\n<li>Studium Physik</li>\n</ul>",
            "t_experience_level": "Senior (7-15 Jahre)",
            "t_maincategory": "Finanzwesen",
            "t_procedure_txt": "",
            "t_salary_period": "pro Jahr",
            "t_specialized_focus": "<ul>\n<li>Budgetplanung und Wirtschaftlichkeitsrechnungen, sowie Erstellung von Entscheidungsvorlagen</li>\n<li>Verantwortung, Gestaltung und Optimierung von Controlling-Prozessen und Tools</li>\n<li>Anfertigung von Monatsreportings und Jahresplanung</li>\n<li>Verantwortung von Lean Management Maßnahmen</li>\n<li>Erfahrung in der Leitung der Buchhaltung und Reorganisation der Abteilung und interner Prozesse</li>\n<li>Verantwortung der Monats- und Jahresabschl&uuml;sse, sowie Bilanzierung nach HGB und IFRS</li>\n<li>Durchf&uuml;hrung von Sanierungsprojekten</li>\n<li>Erste Ber&uuml;hrungsunkte zum Immobiliensektor mit Schwerpunkt auf die Assetklasse Gewerbe</li>\n</ul>"
        }
    },
    {
        "id": "5949249257",
        "properties": {
            "custom_talent_category": "Fonds & Portfolio Management",
            "hs_createdate": "12/06/24",
            "hs_lastmodifieddate": "14/05/25",
            "hs_object_id": "5949249257",
            "t_availability": "6 Monate verhandelbar",
            "t_candidate_id": "10683",
            "t_city": "Raum Düsseldorf",
            "t_current_position": "Portfolio Manager / Immobilienmanagement",
            "t_current_position_group": "Immobilienwesen",
            "t_desired_region_1": "Nordrhein-Westfalen",
            "t_desired_region_2": "Nordrhein-Westfalen",
            "t_desired_salary": "105000",
            "t_education_background": "<ul>\n<li>Weiterbildung zum lizensierten DGNB ESG-Manager</li>\n<li>Diplom Diplom-&Ouml;konom</li>\n<li>Fachhochschulreife Allgemeine Hochschulreife</li>\n</ul>",
            "t_experience_level": "Senior (7-15 Jahre)",
            "t_maincategory": "Immobilienwesen",
            "t_procedure_txt": "",
            "t_salary_period": "pro Jahr",
            "t_specialized_focus": "<ul>\n<li>Ganzheitliche Verantwortung des Controllings der betreuten Fondsvehikel</li>\n<li>ESG: Analyse & Bewertung des Immobilienportfolios (EU-Taxonomie, Nachhaltigkeit der Investitionsentscheidungen)</li>\n<li>Finanz- und Liquidit&auml;tsplanung f&uuml;r die Fonds</li>\n<li>Unterst&uuml;tzung der Investitions- und Desinvestitionsentscheidungen</li>\n<li>Bearbeitung von Anfragen von institutionellen Investoren</li>\n<li>Vorbereitung der Quartals- und Jahresabschl&uuml;sse</li>\n<li>Datenplausibilisierung der Fonds</li>\n<li>Optimierung des Reportings und der jeweils beteiligten Schnittstellen</li>\n</ul>"
        }
    },
    {
        "id": "6109924804",
        "properties": {
            "custom_talent_category": "Volljuristen",
            "hs_createdate": "18/06/24",
            "hs_lastmodifieddate": "14/05/25",
            "hs_object_id": "6109924804",
            "t_availability": "3 Monate zum Monatsende",
            "t_candidate_id": "49585",
            "t_city": "Kiel, Hamburg, Norddeutschland",
            "t_current_position": "Rechtsanwältin",
            "t_current_position_group": "Recht",
            "t_desired_region_1": "Schleswig-Holstein",
            "t_desired_region_2": "Hamburg",
            "t_desired_salary": "75000",
            "t_education_background": "<ul>\n<li>Promotion</li>\n<li>Volljuristin</li>\n<li>Staatsexamen zweites: 6,72</li>\n<li>Staatsexamen erstes: 10,27</li>\n<li>Allgemeine Hochschulreife</li>\n</ul>",
            "t_experience_level": "Medior (3-7 Jahre)",
            "t_maincategory": "Recht",
            "t_procedure_txt": "",
            "t_salary_period": "pro Jahr",
            "t_specialized_focus": "<ul>\n<li>Projekteins&auml;tze mit dem Fokus &ouml;ffentliches Wirtschaftsrecht</li>\n<li>Pr&uuml;fung von Wiederspruchverfahren und &Uuml;berbr&uuml;ckungshilfen</li>\n<li>Pr&uuml;fung von deutschen, englischen und russischen juristischen Schrifts&auml;tzen</li>\n<li>Forensische Untersuchungen mit dem Fokus auf der Energiebranche</li>\n</ul>"
        }
    },
    {
        "id": "6110021868",
        "properties": {
            "custom_talent_category": "Volljuristen, Volljuristen [BIR]",
            "hs_createdate": "18/06/24",
            "hs_lastmodifieddate": "17/04/25",
            "hs_object_id": "6110021868",
            "t_availability": "3 Monate zum Monatsende",
            "t_candidate_id": "49201",
            "t_city": "Wuppertal, Düsseldorf, Köln",
            "t_current_position": "Counsel",
            "t_current_position_group": "Recht",
            "t_desired_region_1": "Nordrhein-Westfalen",
            "t_desired_salary": "140000",
            "t_education_background": "<ul>\n<li>Volljuristin</li>\n<li>Staatsexamen zweites: 9,85</li>\n<li>Staatsexamen erstes: 8,49</li>\n<li>Allgemeine Hochschulreife</li>\n</ul>",
            "t_experience_level": "Senior (7-15 Jahre)",
            "t_maincategory": "Recht",
            "t_procedure_txt": "",
            "t_salary_period": "pro Jahr",
            "t_specialized_focus": "<ul>\n<li>Langj&auml;hrige Expertise aus der Beratung nationaler und internationaler Mandanten zu allen Fragen des Immobilienrechts aller Asset Klassen (aktuell besonders im Bereich Logistik) mit besonderem Fokus auf (grenz&uuml;berschreitenden) Immobilientransaktionen</li>\n<li>Beratung im Legal Asset Management, gewerblichen Miet- und Pachtrecht, Unterst&uuml;tzung im Bereich Property Management sowie Grundst&uuml;cksrecht</li>\n<li>Vertragserstellung, Pr&uuml;fung und Verhandlung, Prozessf&uuml;hrung</li>\n<li>Rechtliche Schwerpunkte: Immobilienwirtschaftsrecht, gewerbliches Mietrecht. Pachtrecht, Wohnraummietrecht, Grundst&uuml;cksrecht</li>\n</ul>"
        }
    },
    {
        "id": "6110024649",
        "properties": {
            "custom_talent_category": "Recht",
            "hs_createdate": "18/06/24",
            "hs_lastmodifieddate": "14/05/25",
            "hs_object_id": "6110024649",
            "t_availability": "3 Monate zum Quartalsende",
            "t_candidate_id": "48688",
            "t_city": "München",
            "t_current_position": "Senior Compliance Officer",
            "t_current_position_group": "Finanzwesen & Personal",
            "t_desired_region_1": "Bayern",
            "t_desired_salary": "130000",
            "t_education_background": "<ul>\n<li>Volljurist</li>\n<li>Staatsexamen zweites</li>\n<li>Staatsexamen erstes</li>\n<li>Allgemeine Hochschulreife</li>\n</ul>",
            "t_experience_level": "Senior (7-15 Jahre)",
            "t_maincategory": "Recht",
            "t_procedure_txt": "",
            "t_salary_period": "pro Jahr",
            "t_specialized_focus": "<ul>\n<li>Operative Compliance Betreuung des Unternehmens</li>\n<li>Bearbeitung von Themen in den Bereichen AFC, Sanktionen, AML, Insider Monitoring sowie die Zuarbeit f&uuml;r Marketingunterlagen</li>\n<li>Knapp 10-j&auml;hrige T&auml;tigkeit mit dem Schwerpunkt Compliance, MaRisk sowie Mitarbeiterf&uuml;hrung f&uuml;r bis zu 8 Mitarbeiter</li>\n<li>Gestaltung und Implementierung der entsprechenden Prozesse und des Compliance Management Systems</li>\n<li>Rechtliche Beratung insbesondere im Hinblick auf regulatorische Entwicklungen im Derivatebereich sowie bei Pensionsgesch&auml;ften und Wertpapierleihe</li>\n</ul>"
        }
    }
]